### ISSUE TITLE
关于输入法在引导页死循环的问题～

### ISSUE THREAD

**Issue by junchenChow** [WiInputMethod/VE#1]
![screenshot_20160803-160718 1](https://cloud.githubusercontent.com/assets/13553319/17358480/c15253cc-5994-11e6-904d-cd4cfdb9f4cd.png)
![screenshot_20160803-160725 1](https://cloud.githubusercontent.com/assets/13553319/17358541/163a43ae-5995-11e6-9354-4041b2e68257.png)
在引导页面 永远过不去 或者是我使用姿势不对 设置输入法我也把当前默认使用的输入法设置成了ve输入发 但是还是跳不过去 而且感觉好像不过这个引导页 输入法也没发用 在用到输入法的地方直接就崩溃了 希望大大指导一下～

**Comment by purebluesong** [comment]
这个是包名没修改完全,以前的包名是 wi.t9改成 ve 以后发现会安装两个 ve现在准备发布决定再改回原来的包名,出现这个问题是因为有些地方包名没有清理干净,我下班以后改改
