### ISSUE TITLE
ai 和 si 混了

### ISSUE THREAD

**Issue by linan20081947** [WiInputMethod/VE#2]

**Comment by purebluesong** [comment]
麻烦具体解释一下？

**Comment by linan20081947** [comment]
输入ai  返回的字里既有ai的字又有si的字 比如四      输入si也是一样，返回两个音的字集

**Comment by purebluesong** [comment]
你是用的QK（全键）的输入模式吧，这个是为了适配手机屏幕比较小，容易误触的特点而出现的。
这是个输入法内核的特点。

**Comment by linan20081947** [comment]
能配置吗？不想要这个功能

**Comment by purebluesong** [comment]
输入法界面没有这个配置，内核应该是可以的，不过时间久远我已经记不得了。。。
